version: '3.8'

volumes:
  user_data:
  images:

services:
  postgresql:
    image: postgres
    volumes:
      - user_data:/var/lib/postgresql/data
      - ./server/initdb:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_PASSWORD: sharpgcu75!@
      POSTGRES_DB: Sharpic
      TZ: Asia/Seoul
  
  server:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - images:/images
    environment:
      POSTGRES_DB: Sharpic
      POSTGRES_HOST: postgresql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sharpgcu75!@
    restart: always
  
  imagesr:
    build:
      context: ./imagesr
      dockerfile: ./cuda.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
              - capabilities: [gpu]
    depends_on:
      - postgresql
    environment:
      HOST: "postgresql"
      DATABASE: "Sharpic"
      USER_SQL: "postgres"
      PASS: "sharpgcu75!@"
      PORT: 5432
    restart: always

  web:
    build: 
      context: ./web
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - postgresql
      - imagesr
    ports:
      - 8007:80

