version: '3.8'

volumes:
  user_data:
  images:

services:
  postgresql:
    image: postgres
    volumes:
      - user_data:/var/lib/postgresql/data
      - ./server/initdb:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_PASSWORD: sharpgcu75!@
      POSTGRES_DB: Sharpic
      TZ: Asia/Seoul
    ports:
      - 5432:5432
  
  server:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - images:/images
    environment:
      POSTGRES_DB: Sharpic
      POSTGRES_HOST: postgresql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sharpgcu75!@
      DOMAIN: sharpic.chromato99.com
    restart: always
    ports:
      - 8005:8005

  web:
    build: 
      context: ./web
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8007:80
  
  # imagesr:
  #   build:
  #     dockerfile: ./imagesr/Dockerfile
  #   restart: always
